name: placement-etudiants
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - libffi
  - zlib
  - sqlite
  - ncurses
  - xz
  - tk
  - readline
  - pip:
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.5
      - attrs==24.2.0
      - babel==2.17.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.1.0
      - faker==37.4.0
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.25.2
      - ipython==8.15.0
      - ipywidgets==8.1.7
      - jinja2==3.1.4
      - json5==0.12.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.10.0.84
      - pandas==2.1.4
      - pillow==10.4.0
      - psutil==6.0.0
      - pyarrow==21.0.0
      - pygments==2.18.0
      - pylance==0.37.0
      - pyparsing==3.1.4
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==26.2.0
      - reportlab==4.2.5
      - requests==2.32.3
      - scipy==1.11.4
      - terminado==0.18.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - tzdata==2024.2
      - urllib3==2.4.0
      - widgetsnbextension==4.0.14
